#!/bin/bash
####################################################################
# Author: weirdcrap						                                     #
# Mail: weirdcrap    [(at)]     protonmail [dot]  com		           #
# Version: 0.2 (beta)						                                   #
# Purpose:							                                           #
# I wrote/tested this in about an hour to enhance the functionality#
# of Sonarr/Radarr's torrent black hole feature to convert .magnet #
# files (links) into a torrent file that rtorrent could natively   #
# import through my specified watch folder while preserving my     #
# custom labels, download directories, etc.			                   #
# If you found this script then you must already know my pain lol  #
#								                                                   #
# Function:							                                           # 
# This loops through all the .magnet files in the directory saved  #
# in $FILES and passes them through to aria2c which takes          #
# the infohash or magnet url and turns it into a .torrent file that#
# rtorrent can then import through its watch folder.               #
####################################################################

####################################################################
# Change log:													                             #
#	v0.1 (beta): Initial release								                     #
#	v0.2 (beta): Switched to aria2c for magnet resolution		         #
####################################################################


####################################################################
# First some general file cleanup for my sanity.                   #
# this just deletes any torrent files older than 2 days            #
# which should gave rtorrent plenty of time to have picked them up.#
####################################################################
find ~/movie-watch/*.torrent -mtime +2 -exec rm {} \;

FILES=~/movie-watch/*.magnet
for f in $FILES
do
  # take action on each file. $f store current file name
  cat $f
  cd ~/movie-watch/
  aria2c --bt-metadata-only=true --bt-save-metadata=true $(cat $f) #passes file contents to aria2c
  rm -f $f
done
